Step two
altimetrik-onboarding-uy/jmcabrera pull request #11
Opened 2020-01-06 20:05 UTC by jCabreraAltimetrik

please check

2020-01-06 20:30 UTC, stefaniaoverman commented on force-app/main/default/triggers/TaskTrigger.trigger
> +        	System.debug('isBefore isInsert');
You should make sure that the code you push doesnt include system.debugs nor console.logs

2020-01-06 20:32 UTC, stefaniaoverman commented on force-app/main/default/classes/TaskTriggerHandler.cls
> +                                   {
I'm pretty sure this nested Ifs can be optimized

2020-01-06 20:35 UTC, stefaniaoverman requested changes

2020-01-06 20:35 UTC, stefaniaoverman commented on force-app/main/default/classes/TaskTriggerHandler.cls
> +                            if(task.ActivityDate != null)
I'm pretty sure this nested Ifs can be optimized

2020-01-08 12:05 UTC, jCabreraAltimetrik commented
Removed System.debug and console.logs; improved upon code removing various nested ifs.

2020-01-08 12:05 UTC, closed without merging